name: Styling
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: npm install

    - name: Store html files
      run: |
        for file in "test/test.tsx" "test/test.ts"; do
          vim -u ./.github/vimrc +TOhtml "+w %" '+qall!' $file > /dev/null
        done

    - name: Generate images
      id: report
      run: |
        node .github/generate-issue-comment.js test/*.html > ./.github/report.md

    - name: Comment on PR
      uses: Schniz/comment-on-pr@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        file_path: ./.github/report.md
        unique_id: VIM_HTML_EXPORTS
